# Generated by Django 5.0.6 on 2024-06-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_image_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://www.pitzer.edu/communications/wp-content/uploads/sites/17/2022/04/blank-profile-picture-1x1-1.jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
