# Generated by Django 5.0.6 on 2024-06-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_image_upload', '0007_alter_activity_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
