# Generated by Django 5.0.6 on 2024-06-17 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_image_upload', '0008_image_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
